director_uuid: BOSH-DIRECTOR-UUID

name: etcd-multi-az-no-ssl

jobs:
- name: etcd_z1
  instances: 2
  networks:
  - name: etcd1
    static_ips:
    - 10.0.22.4
    - 10.0.22.5
  resource_pool: etcd_z1
  persistent_disk: 1024
  templates:
  - release: etcd
    name: etcd
- name: etcd_z2
  instances: 1
  networks:
  - name: etcd2
    static_ips:
    - 10.0.23.4
  resource_pool: etcd_z2
  persistent_disk: 1024
  templates:
  - release: etcd
    name: etcd

networks:
- name: etcd1
  type: manual
  subnets:
  - reserved:
    - 10.0.22.2-10.0.22.3
    - 10.0.22.12-10.0.22.254
    static:
    - 10.0.22.4
    - 10.0.22.5
    cloud_properties:
      name: "etcd1"
      subnet: "subnet-56d4600e"
    gateway: 10.0.22.1
    range: 10.0.22.0/24
- name: etcd2
  type: manual
  subnets:
  - reserved:
    - 10.0.23.2-10.0.23.3
    - 10.0.23.12-10.0.23.254
    static:
    - 10.0.23.4
    cloud_properties:
      name: "etcd2"
      subnet: "subnet-33b61419"
    gateway: 10.0.23.1
    range: 10.0.23.0/24

compilation:
  cloud_properties:
    instance_type: c3.large
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 2048
      type: gp2
  network: etcd1
  reuse_compilation_vms: true
  workers: 3

update:
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000
  canaries: 1

resource_pools:
- name: etcd_z1
  network: etcd1
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.medium
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 1024
      type: gp2
- name: etcd_z2
  network: etcd2
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.medium
    availability_zone: us-east-1c
    ephemeral_disk:
      size: 1024
      type: gp2

properties:
  etcd:
    machines:
    - 10.0.22.4
    - 10.0.22.5
    - 10.0.23.4
    peer_require_ssl: false
    require_ssl: false
    heartbeat_interval_in_milliseconds: 50

releases:
- name: etcd
  version: latest
